---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs

Image:
  extensions:
    - 'Greyscaled'
Member:
  lock_out_after_incorrect_logins: 3
Director:
  environment_type: 'live'
GDBackend:
  default_quality: 60
---
Only:
  environment: 'live'
---
Email:
  admin_email: 'simon@casa-laguna.net'

#Zauberfisch demands: no theme folder, so here we go ;)
#SSViewer:
#  theme: 'simple'
