---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs

#Zauberfisch demands: no theme folder, so here we go ;)
#SSViewer:
#  theme: 'simple'